# Generated by Django 6.0.4 on 2026-04-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycsubmission_clarification_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('pan', 'PAN Card'), ('aadhaar', 'Aadhaar Card'), ('bank_statement', 'Bank Statement'), ('additional_info', 'Additional Information')], max_length=30),
        ),
    ]
